apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xavia-ota.fullname" . }}-secret
  labels:
    {{- include "xavia-ota.labels" . | nindent 4 }}
type: Opaque
data:
  PRIVATE_KEY_BASE_64: {{ .Values.config.privateKeyBase64 | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.config.adminPassword | b64enc | quote }}
  {{- if and (eq .Values.config.database.type "postgres") (.Values.config.database.postgres.password.value) }}
  POSTGRES_PASSWORD: {{ .Values.config.database.postgres.password.value | b64enc | quote }}
  {{- end }}
  {{- if or (eq .Values.config.blobStorage.type "supabase") (eq .Values.config.database.type "supabase") }}
  SUPABASE_API_KEY: {{ .Values.config.database.supabase.apiKey | b64enc | quote }}
  {{- end }}  
  {{- if and (eq .Values.config.blobStorage.type "gcs") .Values.config.blobStorage.gcs.serviceAccount.credentialsJson }}
  service-account.json: {{ .Values.config.blobStorage.gcs.serviceAccount.credentialsJson | quote }}
  {{- end }}
