# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xavia-ota.fullname" . }}
  labels: 
    {{- include "xavia-ota.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector: 
    {{- include "xavia-ota.selectorLabels" . | nindent 4 }}
