name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: npm
        run: npm install
        working-directory: ./
      - name: tsc
        run: npx tsc
        working-directory: ./
      - name: Lint
        run: npm run lint
        working-directory: ./
      - name: Test
        run: npm run test
        working-directory: ./
